spring.application.name=CourseApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/allanmcc9
spring.datasource.username=postgres
spring.datasource.password=password
#logging.level.org.springframework.security=TRACE